services:
  db:
    image: pgvector/pgvector:pg17
    container_name: dev-blog-postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${PG_EXTERNAL_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: dev-blog-redis
    restart: always
    ports:
      - "${REDIS_EXTERNAL_PORT}:6379"

  pgadmin:
    image: dpage/pgadmin4
    container_name: dev-blog-pgadmin
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: dev-backend-go-app
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./backend:/app
    restart: always
    depends_on:
      - db
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
  caddy:
    container_name: caddy
    image: docker.io/library/caddy:2-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data:rw
      - caddy-config:/config:rw
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
  
  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: searxng
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./searxng:/etc/searxng:rw
      - searxng-data:/var/cache/searxng:rw
    environment:
      - SEARXNG_SECRET=${SEARXNG_SECRET:-default}
      - SEARXNG_BASE_URL=http://searxng:8080/search
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

volumes:
  postgres_data:
  searxng-data:
  caddy-data:
  caddy-config:

