services:
  db:
    image: pgvector/pgvector:pg17
    container_name: blog-postgres-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${EXTERNAL_IP}:${PG_EXTERNAL_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

  redis:
    image: redis:7
    container_name: blog-redis-db
    restart: always
    ports:
      - "127.0.0.1:${REDIS_EXTERNAL_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - internal

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: blog-backend-go-app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      REDIS_HOST: redis
      REDIS_PORT: 6379
      APP_ENV: ${APP_ENV}
      GIN_MODE: release
    ports:
      - "127.0.0.1:5432"
    depends_on:
      - db
      - redis
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - internal
      - public
      - ollama_net
    volumes:
      - ./backend/cmd/server/logs:/app/logs

  frontend:
    container_name: blog-frontend-nextjs-app
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    ports:
        - "127.0.0.1:9009:3000"
    depends_on:
      - backend
    restart: always
    networks:
      - public


volumes:
  postgres_data:
  redis_data:
  

networks:
  internal:
    driver: bridge
  public:
    driver: bridge
  ollama_net:
    external: true
